apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: image-name
      type: string
  tasks:
    - name: npminstall
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: tests
      runAfter: ["npminstall"]
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      runAfter: ["tests"]
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: pipeline-workspace